### PR TITLE
Fix author's name

### PR DESCRIPTION
**Pull request by belochub**
Use Ukrainian name and official Ukrainian transliteration instead of Russian variant of the name.

### CODE REVIEW

**Review by aqrln — CHANGES_REQUESTED** [review]
Update the `AUTHORS` file too.

**Comment by belochub** [comment]
@aqrln, updated.

**Review by aqrln — APPROVED** [review]

**Comment by aqrln** [comment]
@belochub can you please rebase it so that the build is not failing?

**Comment by belochub** [comment]
@aqrln, rebased.

**Comment by belochub** [comment]
Landed in cdf8e02c6026e297292f920c57e7170927703593.

**Pull request closed without merging**
