### PR TITLE
Just a few code style changes

### PR DESCRIPTION
**Pull request by tshemsedinov**

### CODE REVIEW

**Comment by DzyubSpirit** [comment]
@tshemsedinov, Could you please describe advantages of using function declaration with `const fn = () => ()` comparing to `function fn() {}` declaration. Because now there is no style guide describing when to use `const fn = () => ()` and when `function fn() {}`

**Comment by tshemsedinov** [comment]
@DzyubSpirit I think lambdas are preferable where possible. If we need no `this` better to use lambdas because lambdas have no object binding thus they are a little faster.

**Comment by belochub** [comment]
I've done some testing and there is no difference in performance between using regular function declarations and using arrow functions when `this` is not used, so I don't think that we need to change this everywhere if the only reason to do so is improving performance.

**Comment by tshemsedinov** [comment]
I'd prefer to use lambdas everywhere if we need no `this` binding just for consistency

**Comment by belochub** [comment]
Okay, I agree with that, if that is needed for consistency, but in the same time I don't understand the need to add parentheses in every arrow function with immediate return, since it doesn't improve consistency, because to improve consistency we need to use braces and explicitly specify `return`, like that:
```javascript
const fn = (a, b) => {
  return a + b;
};
```
instead of
```javascript
const fn = (a, b) => a + b;
```
and since the former option is forbidden by the `eslint` config, I don't see the need to turn the latter variant into
```javascript
const fn = (a, b) => (
  a + b
);
```
since it does not improve readability and only increases confusion instead, since it makes the function's body on the second line look like an unfinished statement (due to the missing semicolon) and enlarges it to 3 lines instead of 1 or 2.

**Comment by tshemsedinov** [comment]
I propose additional parentheses only to long functions that can't fit in single line. Just for comparison:
```js
const pathFunctionsWrapper = (func, path) => (p, ...args) => (
  func(makeFsArgSafe(p, path), ...args)
);
```
and
```js
const pathFunctionsWrapper = (func, path) => (p, ...args) =>
  func(makeFsArgSafe(p, path), ...args);
```
or
```js
const pathFunctionsWrapper = (func, path) =>
  (p, ...args) =>
    func(makeFsArgSafe(p, path), ...args);
```
I think that all styles for such functions will be far from good readability.

**Comment by belochub** [comment]
The second and third variants are both okay with me, I don't see the need to lengthen the function's body even more by adding parentheses if it can't fit on a single line.

**Comment by tshemsedinov** [comment]
Agree @belochub

**Review by belochub — APPROVED** [review]

**Comment by belochub** [comment]
Landed in https://github.com/metarhia/sandboxed-fs/commit/11b81804e3769a3bef0b3738179d66dc882a58a4.

**Pull request closed without merging**
