### PR TITLE
Package maintenance

### PR DESCRIPTION
**Pull request by timursevimli**
Now sandbox-fs module can work and wrap fs.promises and we can use it with the await keyword.

For example:

```javascript
const sandboxedFs = require('.');
const fs = sandboxedFs.bind('./test');

const someAsyncFunction = async () => {
try {
 const data = await fs.promises.readFile('../../file.ext', 'utf8');
  console.log(data.toString());
} catch (e) {
  throw e;
}

someAsyncFunction();
```

### CODE REVIEW

**Comment by timursevimli** [comment]
retrigger checks

**Review by tshemsedinov — CHANGES_REQUESTED** [review]
We can't drop `fs.exists` support, even deprecated it is still supported for node.js 20.x

**Review by tshemsedinov — APPROVED** [review]
LGTM

**Comment by tshemsedinov** [comment]
Landed in https://github.com/metarhia/sandboxed-fs/commit/3ac8ded17d35c3258a4714fea872e54092773872, https://github.com/metarhia/sandboxed-fs/commit/768870bd32f5e0240a78128db0da7cd1077f4883, https://github.com/metarhia/sandboxed-fs/commit/e2ce30a1f30aa82a0c211869506ff2cd71d7f058, https://github.com/metarhia/sandboxed-fs/commit/d18fd89aadd9cd85c4dfc160651e84459367c855, and https://github.com/metarhia/sandboxed-fs/commit/6004d6798c6f4019bbfe0d6e5f7fdbeca70c8962

**Pull request closed without merging**
